### ISSUE TITLE
App logo and Title

### ISSUE THREAD

**Issue by iakash-singh** [MSTC-DA-IICT/Hacktoberfest23-Expense-Tracker-app-Flutter#1]
Summary:
We need to update our app's logo and title to reflect our evolving brand and enhance the overall user experience.
1. Give an appropriate name to the app.
2. Change the Logo of the app. By default, you will get the Flutter logo when running the app but you must change the logo according to the app name.

**Comment by Dev-Adnani** [comment]
@iakash-singh Sorry Forgot To Inform That I Want To Solve The Issue , Please Assign It To Me
