### ISSUE TITLE
No State Management

### ISSUE THREAD

**Issue by Moinuddin9777** [MSTC-DA-IICT/Hacktoberfest23-Expense-Tracker-app-Flutter#18]
To have better control over the app it is a must to add state management.   
Keeping in mind the level of complexity for beginners, 
we can use any one of the below :
- GetX 
- Riverpod 
- Provider

**Comment by Moinuddin9777** [comment]
@iakash-singh  can you add hacktober tag to this and assign me this issue

**Comment by sakshipatil4403** [comment]
@iakash-singh can u pls assign me this issue

**Comment by Moinuddin9777** [comment]
> @iakash-singh can u pls assign me this issue

@sakshipatil4403  I am already working on this part
If you would like to work I have to stop it from my side to avoid merge conflicts

**Comment by iakash-singh** [comment]
You both can work on this issue and we will select the best one.

**Comment by Moinuddin9777** [comment]
@iakash-singh 
Please don't forget to add hacktober tag to the PRs before merging.
Thanks
