### ISSUE TITLE
Card to add expenses 

### ISSUE THREAD

**Issue by iakash-singh** [MSTC-DA-IICT/Hacktoberfest23-Expense-Tracker-app-Flutter#2]
Summary:
We need to implement the expense tracking functionality in our Expense Tracker app to help users manage their finances effectively.
1. Create a card so that the user can add expenses
![eafd870b-01ed-4bf3-a38b-ca28091982cd](https://github.com/MSTC-DA-IICT/Hacktoberfest23-Expense-Tracker-app-Flutter/assets/77776282/71f06ef6-a33e-4564-8ccd-72f5e9ffadee)
*The image is attached for the reference.
*You can use your creativity to do this. It is not required to build the same as shown above it is only for reference.

Design Guidelines:

Follow our app's existing design principles and user interface.
Ensure a user-friendly experience for adding and managing expenses.
Implement categories or tags to help users organize their expenses.

Additional Information:

This feature is crucial for improving the utility of our app and providing users with a comprehensive expense management solution.
Consider using relevant libraries to efficiently manage expenses and data.

**Comment by Sagar-Krish1305** [comment]
I am looking forward to solve this issue.

**Comment by Sagar-Krish1305** [comment]
I have added some of the required thing like Name Amount Tags. Now can you tell me the next procedure?

I just push this changes to my Branch. Now, do I need to do anything else?

**Comment by 10maysingh** [comment]
This issue has been resolved.
