### ISSUE TITLE
Design and Implement Splash Screen

### ISSUE THREAD

**Issue by iakash-singh** [MSTC-DA-IICT/Hacktoberfest23-Expense-Tracker-app-Flutter#9]
Summary:
We need to design and implement a splash screen for our app to provide users with a visually appealing and branded loading experience.

Scope:
The scope of this issue includes:

Designing a captivating and on-brand splash screen image or animation.
Implementing the splash screen logic to display it when the app is launched.
Configuring the splash screen's duration to ensure a smooth transition to the main app interface.

**Comment by lochanikalidasu** [comment]
> Summary: We need to design and implement a splash screen for our app to provide users with a visually appealing and branded loading experience.
> 
> Scope: The scope of this issue includes:
> 
> Designing a captivating and on-brand splash screen image or animation. Implementing the splash screen logic to display it when the app is launched. Configuring the splash screen's duration to ensure a smooth transition to the main app interface.

I am interested and have various ideas on implementing a splash Screen for this project. It is my request to kindly allot this page to me for providing a fulfilling solution to the problem.

**Comment by Dev-Adnani** [comment]
@lochanikalidasu This Task Was Assigned To Me , I have completed it beforehand

**Comment by iakash-singh** [comment]
@lochanikalidasu, @Dev-Adnani is right we have already assigned this issue to him and he has completed this task. Could you please look into the other issues and solve them?

**Comment by lochanikalidasu** [comment]
sure . Thank you ,I will explore more issues and try addressing them
innovatively. I haven't seen that the particular issue was assigned. Sorry
for the inconvenience

regards,
lochanikalidasu

**Comment by iakash-singh** [comment]
@lochanikalidasu we have open the issue once again and you are good to go.

**Comment by Dev-Adnani** [comment]
Opening This Issue Again Wont Hamper My Progress In Hacktoberfest ?

**Comment by lochanikalidasu** [comment]
I have no clue regarding this, but anyways I will not be working ahead on
this issue as it has been already allotted.

**Comment by iakash-singh** [comment]
> Opening This Issue Again Wont Hamper My Progress In Hacktoberfest ?

We are looking for more creative idea's and your implementation is very basic
So try to improve that and we will close the issue by your solution only.
